apiVersion: v1
kind: Service
metadata:
  name: cdn-cdnctlmgr
  labels:
    app: cdn
    tier: cdnctlmgr
spec:
  type: NodePort
  ports:
  - port: 9968
  selector:
    app: cdn
    tier: cdnctlmgr
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cdn-cdnctlmgr
  labels:
    app: cdn
    tier: cdnctlmgr
spec:
  selector:
    matchLabels:
      app: cdn
      tier: cdnctlmgr
  replicas: 1
  template:
    metadata:
      labels:
        app: cdn
        tier: cdnctlmgr
    spec:
      initContainers:
      - name: init-conf
        image: busybox
        env:
        - name: CDN_DB_HOST
          value: cdn-mysql-0.cdn-mysql
        command: 
        - sh
        - "-c"
        - |
          set -ex
          # 将config-volume中的配置文件拷贝到conf中
          cp /config-volume/* /conf
          # 替换配置文件中的ip
          DB_IP=$(nslookup $CDN_DB_HOST | tail -n 1| awk '{print $3}')
          sed -i "s/127.0.0.1/$DB_IP/g" /conf/cdnctlmgr.conf
          # 替换为域名
          # sed -i "s/127.0.0.1/$CDN_DB_HOST/g" /conf/cdnctlmgr.conf
        volumeMounts:
        - name: conf
          mountPath: /conf
        - name: config-volume
          mountPath: /config-volume
      - name: init-db
        image: mysql:5.6
        env:
        - name: CDN_DB_HOST
          value: cdn-mysql-0.cdn-mysql
        command:
        - sh
        - "-c"
        - |
          # set -ex
          # 等待mysqld启动
          until mysql -h $CDN_DB_HOST -e "SELECT 1"; do sleep 1; done
          # 创建数据库
          mysql -h $CDN_DB_HOST << EOF
          create database cdnctlmgrcenter;
          create database monitorcenter;
          EOF
          # 初始化数据库
          mysql -h $CDN_DB_HOST cdnctlmgrcenter</db/cdnctlmgrcenter.sql
          mysql -h $CDN_DB_HOST monitorcenter</db/monitorcenter.sql
        volumeMounts:
        - name: db-volume
          mountPath: /db
      containers:
      - name: cdn-cdnctlmgr
        image: zhangmin/p2p/cdn
        workingDir: /opt/server/cdn/CdnCtlMgrCenter
        command: ['sh', '-c', './CdnCtlMgrCenter -l']
        imagePullPolicy: IfNotPresent # 从本地拉取镜像
        ports:
        - containerPort: 9968
          name: tcp
        volumeMounts:
        - name: conf
          mountPath: /opt/server/cdn/CdnCtlMgrCenter/conf
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-volume
        configMap:
          name: configmap-cdnctlmgr-conf
      - name: db-volume
        configMap:
          name: configmap-cdnctlmgr-db                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 