apiVersion: v1
kind: Service
metadata:
  name: cdn-mysql
  labels:
    app: cdn
spec:
  ports:
    - port: 3306
  selector:
    app: cdn
    tier: mysql
  clusterIP: None
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   labels:
#     app: cdn
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: StatefulSet
metadata:
  name: cdn-mysql
  labels:
    app: cdn
spec:
  # required field for StatefulSet
  serviceName: "cdn-mysql"
  replicas: 2
  selector:
    matchLabels:
      app: cdn
      tier: mysql
  template:
    metadata:
      labels:
        app: cdn
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        # - name: MYSQL_ROOT_PASSWORD
        #   value: "root"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
        # hostPath:
            # path: /data
            # type: Directory
        # persistentVolumeClaim:
        #   claimName: mysql-pv-claim
